version: '3.8'

services:
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - rosen_network
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 10s
      timeout: 5s
      retries: 3

  service:
    image: ghcr.io/rosen-bridge/watcher-service:${WATCHER_IMAGE_VERSION:-latest}
    ports:
      - 127.0.0.1:${SERVICE_PORT:-3000}:3000
    environment:
      - POSTGRES_HOST=db
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./config/local.yaml
        target: /app/config/local.yml
      - ./logs/:/app/logs/
    networks:
      - rosen_network
    restart: always
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'curl --fail http://localhost:3000/health/status || exit 1']
      interval: 10s
      timeout: 5s
      retries: 3

  ui:
    image: ghcr.io/rosen-bridge/ui-watcher:${UI_IMAGE_VERSION:-latest}
    networks:
      - rosen_network
    restart: always
    ports:
      - 127.0.0.1:${UI_PORT:-3030}:80
    volumes:
      - nginx-logs:/var/log/nginx
    depends_on:
      service:
        condition: service_healthy

volumes:
  postgres-data:
  nginx-logs:

networks:
  rosen_network:
